spring.cloud.stream:
  bindings:
    process1-in-0:
      destination: words
    process1-out-0:
      destination: counts
    process2-in-0:
      destination: words
    process2-out-0:
      destination: counts

  kafka.streams.bindings.process1-in-0.consumer.application-id: process1-${random.int}
  kafka.streams.bindings.process2-in-0.consumer.application-id: process2-${random.int}
  
  kafka:
    streams:
      binder:
        configuration:
         commit.interval.ms: 100
         default:
          key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#Enable metrics
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health
#Enable logging to debug for spring kafka config
logging:
  level:
    org.springframework.kafka.config: debug
